# Loading dependecies

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import MinMaxScaler 
from sklearn.metrics import root_mean_squared_error, mean_absolute_error #for metric/model evaluation in regression
from sklearn.ensemble import RandomForestRegressor
import pickle

# Read  dataset

In [3]:
df = pd.read_excel("employee_data.xlsx")

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Gender           30 non-null     str
 1   Age              30 non-null     int64
 2   W_Experience     30 non-null     int64
 3   Qualifications   30 non-null     str
 4   Grade            30 non-null     str
 5   Salary           30 non-null     int64
 6   Department       30 non-null     str
 7   Employment_Type  30 non-null     str
 8   Marital_Status   30 non-null     str
 9   Location         30 non-null     str
dtypes: int64(3), str(7)
memory usage: 3.8 KB

In [5]:
df.isna().sum()

Gender             0
Age                0
W_Experience       0
Qualifications     0
Grade              0
Salary             0
Department         0
Employment_Type    0
Marital_Status     0
Location           0
dtype: int64

In [6]:
le = LabelEncoder()

In [7]:
df.Gender = le.fit_transform(df.Gender)

In [8]:
df.Qualifications = le.fit_transform(df.Qualifications)

In [9]:
df.Grade = le.fit_transform(df.Grade)

In [10]:
df.Department = le.fit_transform(df.Department)

In [11]:
df.Employment_Type = le.fit_transform(df.Employment_Type)

In [13]:
df.Marital_Status = le.fit_transform(df.Marital_Status)

In [19]:
df.Location = le.fit_transform(df.Location)

In [26]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Gender           30 non-null     int64
 1   Age              30 non-null     int64
 2   W_Experience     30 non-null     int64
 3   Qualifications   30 non-null     int64
 4   Grade            30 non-null     int64
 5   Salary           30 non-null     int64
 6   Department       30 non-null     int64
 7   Employment_Type  30 non-null     int64
 8   Marital_Status   30 non-null     int64
 9   Location         30 non-null     int64
dtypes: int64(10)
memory usage: 2.5 KB

In [28]:
df.describe()

,Gender,Age,W_Experience,Qualifications,Grade,Salary,Department,Employment_Type,Marital_Status,Location
count,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.00000
mean,0.500000,34.633333,9.700000,1.533333,4.466667,285166.666667,6.100000,0.833333,0.433333,3.20000
std,0.508548,7.218192,6.401239,1.382984,2.596195,131637.454929,4.543658,0.379049,0.504007,2.21904
min,0.000000,24.000000,1.000000,0.000000,0.000000,115000.000000,0.000000,0.000000,0.000000,0.00000
25%,0.000000,29.000000,5.000000,0.000000,3.000000,181250.000000,2.250000,1.000000,0.000000,1.00000
50%,0.500000,33.500000,8.500000,1.000000,4.500000,260000.000000,5.000000,1.000000,0.000000,4.00000
75%,1.000000,39.750000,13.750000,2.000000,6.750000,383750.000000,10.000000,1.000000,1.000000,5.00000
max,1.000000,50.000000,24.000000,4.000000,9.000000,560000.000000,14.000000,1.000000,1.000000,6.00000

In [30]:
df.columns

Index(['Gender', 'Age', 'W_Experience', 'Qualifications', 'Grade', 'Salary',
       'Department', 'Employment_Type', 'Marital_Status', 'Location'],
      dtype='str')

In [32]:
mm = MinMaxScaler()

In [34]:
df.describe()

,Gender,Age,W_Experience,Qualifications,Grade,Salary,Department,Employment_Type,Marital_Status,Location
count,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.00000
mean,0.500000,34.633333,9.700000,1.533333,4.466667,285166.666667,6.100000,0.833333,0.433333,3.20000
std,0.508548,7.218192,6.401239,1.382984,2.596195,131637.454929,4.543658,0.379049,0.504007,2.21904
min,0.000000,24.000000,1.000000,0.000000,0.000000,115000.000000,0.000000,0.000000,0.000000,0.00000
25%,0.000000,29.000000,5.000000,0.000000,3.000000,181250.000000,2.250000,1.000000,0.000000,1.00000
50%,0.500000,33.500000,8.500000,1.000000,4.500000,260000.000000,5.000000,1.000000,0.000000,4.00000
75%,1.000000,39.750000,13.750000,2.000000,6.750000,383750.000000,10.000000,1.000000,1.000000,5.00000
max,1.000000,50.000000,24.000000,4.000000,9.000000,560000.000000,14.000000,1.000000,1.000000,6.00000

In [36]:
df1 = mm.fit_transform(df)

In [38]:
df1

array([[1.        , 0.15384615, 0.13043478, 0.        , 0.33333333,
        0.15730337, 0.        , 1.        , 1.        , 0.83333333],
       [0.        , 0.30769231, 0.26086957, 0.25      , 0.44444444,
        0.23595506, 0.21428571, 1.        , 0.        , 0.        ],
       [1.        , 0.65384615, 0.60869565, 0.5       , 0.77777778,
        0.66292135, 0.35714286, 1.        , 0.        , 0.83333333],
       [0.        , 0.07692308, 0.04347826, 1.        , 0.11111111,
        0.04494382, 0.07142857, 0.        , 1.        , 1.        ],
       [1.        , 0.42307692, 0.39130435, 0.        , 0.55555556,
        0.38202247, 0.28571429, 1.        , 0.        , 0.33333333],
       [0.        , 0.19230769, 0.17391304, 0.75      , 0.22222222,
        0.1011236 , 1.        , 1.        , 1.        , 0.16666667],
       [1.        , 0.84615385, 0.82608696, 0.5       , 0.88888889,
        0.82022472, 0.78571429, 1.        , 0.        , 0.66666667],
       [0.        , 0.53846154, 0.47826087, 0.        , 0.66666667,
        0.50561798, 0.71428571, 1.        , 0.        , 0.83333333],
       [1.        , 0.23076923, 0.2173913 , 0.25      , 0.33333333,
        0.17977528, 0.85714286, 1.        , 1.        , 0.        ],
       [0.        , 0.73076923, 0.69565217, 0.5       , 0.77777778,
        0.69662921, 0.21428571, 1.        , 0.        , 0.83333333],
       [1.        , 0.11538462, 0.08695652, 1.        , 0.11111111,
        0.05617978, 0.5       , 0.        , 1.        , 0.5       ],
       [0.        , 0.38461538, 0.34782609, 0.        , 0.55555556,
        0.40449438, 0.35714286, 1.        , 0.        , 0.        ],
       [1.        , 0.57692308, 0.52173913, 0.25      , 0.66666667,
        0.48314607, 0.14285714, 1.        , 0.        , 1.        ],
       [0.        , 0.03846154, 0.        , 0.75      , 0.        ,
        0.01123596, 0.        , 0.        , 1.        , 0.33333333],
       [1.        , 1.        , 1.        , 0.5       , 1.        ,
        1.        , 0.64285714, 1.        , 0.        , 0.83333333],
       [0.        , 0.26923077, 0.2173913 , 0.25      , 0.33333333,
        0.20224719, 0.07142857, 1.        , 1.        , 0.16666667],
       [1.        , 0.46153846, 0.43478261, 0.        , 0.55555556,
        0.41573034, 0.92857143, 1.        , 0.        , 0.        ],
       [0.        , 0.80769231, 0.7826087 , 0.5       , 0.88888889,
        0.85393258, 0.28571429, 1.        , 0.        , 0.83333333],
       [1.        , 0.34615385, 0.30434783, 1.        , 0.33333333,
        0.16853933, 0.57142857, 1.        , 0.        , 0.66666667],
       [0.        , 0.5       , 0.47826087, 0.        , 0.66666667,
        0.52808989, 0.42857143, 1.        , 0.        , 0.        ],
       [1.        , 0.        , 0.        , 0.75      , 0.        ,
        0.        , 1.        , 0.        , 1.        , 0.83333333],
       [0.        , 0.15384615, 0.13043478, 0.        , 0.33333333,
        0.14606742, 0.71428571, 1.        , 1.        , 0.33333333],
       [1.        , 0.69230769, 0.65217391, 0.25      , 0.77777778,
        0.62921348, 0.78571429, 1.        , 0.        , 1.        ],
       [0.        , 0.23076923, 0.17391304, 1.        , 0.22222222,
        0.11235955, 0.85714286, 1.        , 1.        , 0.5       ],
       [1.        , 0.92307692, 0.91304348, 0.5       , 1.        ,
        0.95505618, 0.35714286, 1.        , 0.        , 0.83333333],
       [0.        , 0.42307692, 0.39130435, 0.        , 0.55555556,
        0.42696629, 0.21428571, 1.        , 0.        , 0.16666667],
       [1.        , 0.19230769, 0.17391304, 0.25      , 0.33333333,
        0.19101124, 0.5       , 1.        , 1.        , 0.        ],
       [0.        , 0.61538462, 0.56521739, 0.5       , 0.77777778,
        0.70786517, 0.        , 1.        , 0.        , 0.83333333],
       [1.        , 0.26923077, 0.26086957, 0.        , 0.44444444,
        0.26966292, 0.14285714, 1.        , 1.        , 1.        ],
       [0.        , 0.11538462, 0.08695652, 0.25      , 0.22222222,
        0.12359551, 0.07142857, 0.        , 1.        , 0.66666667]])

In [40]:
df = pd.DataFrame(df1, columns=['Gender', 'Age', 'W_Experience', 'Qualifications', 'Grade', 'Salary',
      'Department', 'Employment_Type', 'Marital_Status', 'Location']) # this convert the df1 into data frame

In [42]:
df.drop("Gender", axis=1, inplace=True)

In [44]:
df.drop("Location", axis=1, inplace=True)

In [46]:
df.drop("Department", axis=1, inplace=True)

In [48]:
df

,Age,W_Experience,Qualifications,Grade,Salary,Employment_Type,Marital_Status
0,0.153846,0.130435,0.00,0.333333,0.157303,1.0,1.0
1,0.307692,0.260870,0.25,0.444444,0.235955,1.0,0.0
2,0.653846,0.608696,0.50,0.777778,0.662921,1.0,0.0
3,0.076923,0.043478,1.00,0.111111,0.044944,0.0,1.0
4,0.423077,0.391304,0.00,0.555556,0.382022,1.0,0.0
5,0.192308,0.173913,0.75,0.222222,0.101124,1.0,1.0
6,0.846154,0.826087,0.50,0.888889,0.820225,1.0,0.0
7,0.538462,0.478261,0.00,0.666667,0.505618,1.0,0.0
8,0.230769,0.217391,0.25,0.333333,0.179775,1.0,1.0
9,0.730769,0.695652,0.50,0.777778,0.696629,1.0,0.0
10,0.115385,0.086957,1.00,0.111111,0.056180,0.0,1.0
11,0.384615,0.347826,0.00,0.555556,0.404494,1.0,0.0
12,0.576923,0.521739,0.25,0.666667,0.483146,1.0,0.0
13,0.038462,0.000000,0.75,0.000000,0.011236,0.0,1.0
14,1.000000,1.000000,0.50,1.000000,1.000000,1.0,0.0
15,0.269231,0.217391,0.25,0.333333,0.202247,1.0,1.0
16,0.461538,0.434783,0.00,0.555556,0.415730,1.0,0.0
17,0.807692,0.782609,0.50,0.888889,0.853933,1.0,0.0
18,0.346154,0.304348,1.00,0.333333,0.168539,1.0,0.0
19,0.500000,0.478261,0.00,0.666667,0.528090,1.0,0.0
20,0.000000,0.000000,0.75,0.000000,0.000000,0.0,1.0
21,0.153846,0.130435,0.00,0.333333,0.146067,1.0,1.0
22,0.692308,0.652174,0.25,0.777778,0.629213,1.0,0.0
23,0.230769,0.173913,1.00,0.222222,0.112360,1.0,1.0
24,0.923077,0.913043,0.50,1.000000,0.955056,1.0,0.0
25,0.423077,0.391304,0.00,0.555556,0.426966,1.0,0.0
26,0.192308,0.173913,0.25,0.333333,0.191011,1.0,1.0
27,0.615385,0.565217,0.50,0.777778,0.707865,1.0,0.0
28,0.269231,0.260870,0.00,0.444444,0.269663,1.0,1.0
29,0.115385,0.086957,0.25,0.222222,0.123596,0.0,1.0

In [126]:
X = df.drop("Salary", axis=1)
y = df.Salary 
X_train, X_test, y_train, y_test = train_test_split(X,y, train_size=0.80, test_size=0.20, random_state=42)

In [128]:
X_train.shape

(24, 6)

In [130]:
X_test.shape

(6, 6)

In [132]:
y_train.shape

(24,)

In [134]:
y_test.shape

(6,)

In [136]:
lr = LinearRegression()

In [138]:
lr.fit(X_train, y_train)

LinearRegression()

In [140]:
predict = lr.predict (X_test)

In [142]:
predict

array([0.59904234, 0.16732589, 0.0591557 , 0.79803569, 0.19849604,
       0.67843645])

In [144]:
mean_absolute_error(predict,y_test)

0.04829306236506714

In [146]:
root_mean_squared_error(predict, y_test)

0.05729813767507129

In [148]:
rf = RandomForestRegressor (n_estimators=100 ) #n_estimator constant

In [150]:
rf.fit(X_train, y_train)

RandomForestRegressor()

In [152]:
result = rf.predict(X_test)

In [154]:
result

array([0.60808989, 0.18042884, 0.11884831, 0.79247191, 0.17726404,
       0.6588764 ])

In [156]:
mean_absolute_error(result, y_test)

0.038301186017478166

In [158]:
root_mean_squared_error(result, y_test)

0.051124434119648655

In [160]:
lr.intercept_

np.float64(-0.0031362790365754845)

In [509]:
lr.coef_

array([-0.81042366,  1.32560144, -0.02004754,  0.60002848, -0.10501716,
        0.01049849])

In [164]:
lr.predict([[12,3,5,7,1,1]])

/opt/anaconda3/lib/python3.12/site-packages/sklearn/utils/validation.py:2830: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([-1.7459729])

In [510]:
filename = "employee data.sav"
with open(filename, "wb") as file:   #this line instruct the filename created to be open with a write only permission
    pickle.dump(rf, file) #rf is the variable name used for the RandomForestEstimator